### ISSUE TITLE
Login button into Navbar for mobile

### ISSUE THREAD

**Issue by ahnafy** [UMM-CSci-3601-S18/iteration-4-megabittron#31]

**Comment by john9hoff** [comment]
I like the sign-out button but I think the sign-in button shouldn't be centered at the bottom of the list. Maybe put it at the top next to menu or move it to the left?

**Comment by john9hoff** [comment]
I think it looks fine. The top part of the navbar looks a little awkward but it isn't a big deal. Also I'm not a huge fan of the plane icon for sign-out!
