### ISSUE TITLE
Charts UX

### ISSUE THREAD

**Issue by Blake376** [UMM-CSci-3601-S18/iteration-4-megabittron#32]
fix UX problems as mentioned by Nic

**Comment by john9hoff** [comment]
I think this looks really great. Good job, man! It's a lot more user friendly and simpler.

My only suggestions are:
-change "the past week" to "Past week" and "the past year" to "Past year"
-indicate to the user somehow that they can click on each emotion to exclude it from the graph
-I don't know if its possible, but there should be a graph already loaded on the page without needing the user to select options. Its good that the options have default presets, but the graph doesn't actually show until they're clicked.
